ChainUrRents/config/routes.rb
Rails.application.routes.draw do
  get "/rents" => "rents#index"
  post "/show" => "rents#show"
  get "/show" => "rents#show"
  root to: redirect('/rents')
end

ChainUrRents/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ChainUrRents/app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :rent
end

ChainUrRents/app/models/rent.rb
class Rent < ActiveRecord::Base
  has_many :bookings, dependent: :destroy
end

ChainUrRents/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ChainUrRents/app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
  end
  def show
    @location = params[:rents][:location]
    @start = params[:rents][:findStart]
    @end = params[:rents][:findEnd]
    puts "jeo" + @start.to_s + @end.to_s + "sdf"
    @rents = Rent.where(:location => @location)
    @rents.each do |rent|
      puts "test" + rent.bookings.to_s
    end
  end
  def find_params
    if !params[:rents].nil?
      params.require(:rents).permit(:location, :findStart, :findEnd)
    end
  end
end

ChainUrRents/app/helpers/application_helper.rb
module ApplicationHelper
end

ChainUrRents/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChainUrRents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ChainUrRents/app/views/rents/index.html.haml
%h1 Find Yourself a place to stay!

- if flash[:notice]
  .alert-message.warning
    %p
      = flash[:notice]

= form_tag '/show' do

  = label :rents, :location, 'City'
  = text_field :rents, :location

  = label :rents, :findStart, 'From'
  = text_field :rents, :findStart

  = label :rents, :findEnd, 'To'
  = text_field :rents, :findEnd

  %br
  %br

  = submit_tag 'Submit'

ChainUrRents/app/views/rents/show.html.haml
%h1 There it is!

%table#lots
  %thead
    %tr
      %th Location
      %th cost
      %th area
      %th floor
      %th services
      %th bookings
  %tbody
    - @rents.each do |rent|
      - number = 0
      - rent.bookings.each do |booking|
        - start = booking.startDate.to_datetime
        - end = booking.endDate.to_datetime
        - range = start..end
        - if range === @start or range === @end then
          number += 1
      -if number>1 then
        %tr
          %td= rent.location
          %td= rent.cost
          %td= rent.area
          %td= rent.floor
          %td= rent.services
          %td= rent.bookings.to_s

= link_to 'Back', rents_path